### ISSUE TITLE
Torch/Cuda error

### ISSUE THREAD

**Issue by HellBoundSinner** [lllyasviel/stable-diffusion-webui-forge#1738]
Hi all,

I did the portable version and the Git Clone of the repository. Whenever I go to start the program, I keep getting errors about Torch/Cuda not being compatible. I have a 3070 Nvidia card. There was another thread in this forum about it. I downloaded Visual Studio and did the MS tools part of it along with the C++ work area. I have tried multiple things, and none of them allow it to work. Any other suggestions because I'm at a loss.

**Comment by Starkiller353** [comment]
Same problem. Reinstalled Forge yesterday and after trying to install Adetailer, the program crashes completely with the same error. Without Adetailer Forge works.

**Comment by HellBoundSinner** [comment]
I wasn't using Adetailer so not sure why it's not working for me.

**Comment by Starkiller353** [comment]
So the problem is not in extensions. Or maybe in some of them.
I also tried to do almost everything to solve this problem, but I failed. I hope someone can help.

**Comment by HellBoundSinner** [comment]
This worked for me finally after someone responded to me on Reddit.

trying installing the latest version of pytorch.

1.  load the python virtual env.
usually <FORGE_FOLDER>\venv\Scripts\activate.bat"
2. Uninstall torch:
pip uninstall torch torchvision torchaudio 

3. Install torch: pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

**Comment by Starkiller353** [comment]
It didn't work for me, unfortunately.
I don't have a venv folder, so I tried skipping 1. and doing 2. and 3. Didn't help.
But thank you for responce.

**Comment by TerminatedProcess** [comment]
I am using StabilityMatrix and have stable diffusion webui forge installed. I get the same error. I tried HellBoundSinner's suggestion but it didn't change anything. Thanks though..

**Comment by Saucermote** [comment]
Mine only broke after the latest update.
