### ISSUE TITLE
RuntimeError: invalid random_device value

### ISSUE THREAD

**Issue by DiegoRRR** [lllyasviel/stable-diffusion-webui-forge#1765]
- I unzipped "webui_forge_cu121_torch21.7z"
- Ran "update.bat"
- Ran "run.bat"
- Had error: `RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.`
- Installed PyTorch for Cuda 11.8 like it said: `python -m pip install torch==2.1.0 torchvision==0.16.0 torchaudio==2.1.0 --index-url https://download.pytorch.org/whl/cu118` (I copied this command from pytorch website)
- And now I have this error:
```
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (
AMD64)]
Version: f2.0.1v1.10.1-previous-526-gc13b26ba
Commit hash: c13b26ba271bac327879d32f01307fc21a012321
Launching Web UI with arguments:
You are using PyTorch below version 2.3. Some optimizations will be disabled.
Traceback (most recent call last):
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\launch.py", line
 54, in <module>
    main()
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\launch.py", line
 50, in main
    start()
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\modules\launch_u
tils.py", line 546, in start
    import webui
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\webui.py", line
17, in <module>
    initialize_forge()
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\modules_forge\in
itialization.py", line 58, in initialize_forge
    from backend import memory_management
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\backend\memory_m
anagement.py", line 133, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\webui\backend\memory_m
anagement.py", line 100, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\system\python\lib\site
-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "D:\apps\stable-diffusion\Forge_20240811_121_21__3\system\python\lib\site
-packages\torch\cuda\__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: invalid random_device value
```

Can someone help, please?

**Comment by drdiggle** [comment]
Which GPU do you use and when was the last time your GPU drivers were updated?

**Comment by DiegoRRR** [comment]
RTX 3060, driver is 474.11. No newer driver can be installed on Windows 7. It does support Cuda 11, that is why I installed PyTorch cu11.8 instead of cu12, like the first error message suggested to do.
This driver is a bit old but the newest version of A1111 doesn't have any problem with it. For Forge is based on A1111, it should not be an issue either.

**Comment by DiegoRRR** [comment]
It says 11.4. I read that 11.4 and 11.8 are compatible because practically nothing changed. Is this the issue?
You mean compiling PyTorch by myself? I don't have any c++ compiler and I never did that. :(

**Comment by drdiggle** [comment]
You can only use up to what your drivers support, 11.8 is compatible with 11.4, but likely not vice-versa. Try installing a newer version of cuda separately. If not, you are likely going have to go down the compilation route. Follow the pytorch organization's build from source instructions, they probably aren't as hard as you think they are, but will take a long time to do the actual compilation.

**Comment by DiegoRRR** [comment]
It was indeed related to a kind of incompatibility with Windows 7.
If someone ever has the same problem, here is how I fixed it:

If you copied "api-ms-win-security-systemfunctions-l1-1-0.dll" to "system32", remove it.

Don't replace the embed python with pythonwin7, it's not necessary anymore. Don't replace any dll either.

Install VxKex (the repo is dead, I don't know which new source is safe to download it from)
In VxKex settings, add Forge's "system/python/python.exe"

Uninstall pytorch, install a compatible pytorch and don't install torchaudio. In "system/python/" open cmd and execute:
python -m pip uninstall Torch Torchvision Torchaudio
python -m pip install torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu118

"LIBOMP140.X86_64.DLL" will be missing, it's a known bug for pytorch 2.4.0. Download it, unzip and copy the dll in system32.
https://www.dllme.com/dll/files/libomp140_x86_64/00637fe34a6043031c9ae4c6cf0a891d

Voila.
