### ISSUE TITLE
RuntimeError: The NVIDIA driver on your system is too old (please help)

### ISSUE THREAD

**Issue by coolpersonidk** [lllyasviel/stable-diffusion-webui-forge#2053]
RuntimeError: The NVIDIA driver on your system is too old (found version 11070). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver.
Press any key to continue . . .
```
what do i do?

**Comment by ferater** [comment]
You can update your graphics card drivers, and it would be better if you provided more detailed information about your graphics card model for better answers.

**Comment by coolpersonidk** [comment]
i fixed it but thanks 👍

**Comment by coolpersonidk** [comment]
it fixed it but thanks 👍

**Comment by raidit** [comment]
> its fixed but thanks 👍

HOW????
People like you should be prisoned for years for finishing treads like THIS! )))))))
