### ISSUE TITLE
It doesn't work with the RTX5080.

### ISSUE THREAD

**Issue by mizossyo** [lllyasviel/stable-diffusion-webui-forge#2601]
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

This message appears when starting up and generation is no longer possible. In other words, since the new GPU RTX5080 does not support CUDA121, I think it is necessary to rebuild the venv with a new version of CUDA. (For example, CUDA126?)

However, when trying to build a venv from user.bat, the file is forcibly built for the CUDA121 environment, which is inconsistent with CUDA126 and makes it impossible to even install.
Can someone please tell me how to solve this?

It may be a problem with the RTX5080 driver...

**Comment by allerias** [comment]
Same issue with RTX5090

**Comment by Guerro26** [comment]
Have the same problem. Maybe nightly build will fix it?
https://github.com/pytorch/pytorch/commit/9232355bb0a935632545daf2d55b16fa38ac0a1f

**Comment by magmirant0011** [comment]
Nvidia spamming that AI AI AI AI everywhere but they cant communicate with real AI programmists to release their card and drivers all compatible with all environements. This should be highlighted everywhere, and people responsible for the lack of support on day 3 of release of that cards should be fired! Or nvidia to just drop so low on stock values that would send them forever to polish AMD shoes.

**Comment by dan4ik94** [comment]
> Nvidia spamming that AI AI AI AI everywhere but they cant communicate with real AI programmists to release their card and drivers all compatible with all environements. This should be highlighted everywhere, and people responsible for the lack of support on day 3 of release of that cards should be fired! Or nvidia to just drop so low on stock values that would send them forever to polish AMD shoes. Not to mention that they released DLSS 4 but only people that know how to correctly install them to games can enjoy the transformer model of dlss. This is really a circus and literally worst release ever of their cards. I was lucky to grab 5080 but i really want right now to sell it so i can forget about headache configuring of that card gave me already.

nobody's gonna communicate anything, there are too many caveats, everyone with their own affairs and schedule. Just wait a week or two, new pytorch pip should drop soon.

**Comment by Panchovix** [comment]
if using linux you can use the cu128 nightly builds, if on windows you have to use the wheels from nvidia on HF

**Comment by mizossyo** [comment]
Thank you.
I downloaded and installed the wheel from nvidia and changed the version in requirements_versions, but it didn't work.
Stupid me!

**Comment by Panchovix** [comment]
not sure if this flag works on forge (it should by the last time i used it), but you can skip on a1111/reforge with --skip-python-version-check

**Comment by rubentorresbonet** [comment]
same issue with 5090

**Comment by yeonpyo3300** [comment]
same with 5080 comfy ui

**Comment by Slider-Override** [comment]
Is there any workaround ?
I am not a expert on this but can we maybe intigrate this into forge?
https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv

If yes, whats the steps ?

**Comment by zlo899nv** [comment]
Update from our NVIDIA team


To use PyTorch for Linux x86_64 on NVIDIA 5080, 5090 Blackwell RTX GPUs  use the latest nightly builds, or the command below.
pip install --pre torch torchvision torchaudio --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)


for Linux SBSA
pip install --pre torch --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)


torchvision and torchaudio for SBSA coming soon


Thanks!

**Comment by Slider-Override** [comment]
> Update from our NVIDIA team
> 
> To use PyTorch for Linux x86_64 on NVIDIA 5080, 5090 Blackwell RTX GPUs use the latest nightly builds, or the command below. pip install --pre torch torchvision torchaudio --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)
> 
> for Linux SBSA pip install --pre torch --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)
> 
> torchvision and torchaudio for SBSA coming soon
> 
> Thanks!

Thanks, but no solution for Windows currently ?

**Comment by rubentorresbonet** [comment]
> > Update from our NVIDIA team
> > To use PyTorch for Linux x86_64 on NVIDIA 5080, 5090 Blackwell RTX GPUs use the latest nightly builds, or the command below. pip install --pre torch torchvision torchaudio --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)
> > for Linux SBSA pip install --pre torch --index-url[ https://download.pytorch.org/whl/nightly/cu128](https://download.pytorch.org/whl/nightly/cu128)
> > torchvision and torchaudio for SBSA coming soon
> > Thanks!
> 
> Thanks, but no solution for Windows currently ?

Have a look here, they talk about windows and docker container: https://github.com/comfyanonymous/ComfyUI/discussions/6643

**Comment by zebulon2** [comment]
> Hi all! Update from our NVIDIA team.
> 
> To use PyTorch for Linux x86_64 and Linux SBSA on NVIDIA 5080, 5090 Blackwell RTX GPUs use the latest nightly builds, or the command below.
> 
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> Stay tuned for further updates
> 
> Thanks!

Thank you. This worked!

**Comment by Natural-Warp** [comment]
looking forward to the windows solution indeed ( SD ForgeUI on 5080 here )

**Comment by magmirant0011** [comment]
> looking forward to the windows solution indeed ( SD ForgeUI on 5080 here )

You need to reinstall torch and torchvision. Enter anaconda prompt, get inside venv of the Forge, uninstall existing torch+torchvision, uninstall xformers if you use it on Forge, download torch+torchvision that is compatible with Blackwell GPU and install it to venv with the anaconda prompt. I did that and now my 5080 can do anything in A111 but in Forge is almost same.

**Comment by magmirant0011** [comment]
> > > looking forward to the windows solution indeed ( SD ForgeUI on 5080 here )
> > 
> > 
> > You need to reinstall torch and torchvision. Enter anaconda prompt, get inside venv of the Forge, uninstall existing torch+torchvision, uninstall xformers if you use it on Forge, download torch+torchvision that is compatible with Blackwell GPU and install it to venv with the anaconda prompt. I did that and now my 5080 can do anything in A111 but in Forge is almost same.
> 
> What's your platform? Linux or Windows?

Win10 Ryzen platform.

**Comment by allerias** [comment]
> > looking forward to the windows solution indeed ( SD ForgeUI on 5080 here )
> 
> You need to reinstall torch and torchvision. Enter anaconda prompt, get inside venv of the Forge, uninstall existing torch+torchvision, uninstall xformers if you use it on Forge, download torch+torchvision that is compatible with Blackwell GPU and install it to venv with the anaconda prompt. I did that and now my 5080 can do anything in A111 but in Forge is almost same.

Can you give some examples of the above commands ?

**Comment by Natural-Warp** [comment]
> torch nightly version for cuda 128/Windows has just been released. I'm guessing the RTX 5080 can run sd webui forge now.

any guidance or tips on how-to ??

**Comment by xiao3612736** [comment]
NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

Operating system: win11 x64
I have tried cu118, cu121, cu126, and also tried changing the RTX5080 graphics card driver, but the problem still cannot be solved.
God, save me!!!

**Comment by allerias** [comment]
I can run forge again after do the following steps:
- Perform a fresh install of ReForge
- Remove Forge venv folder
- Copy the venv folder of Reforge into the Forge directory

**Comment by Natural-Warp** [comment]
> A clean install of ReForge worked for me flawlessly on windows, it automatically downloads the nightly cu128 version for windows.

Can you post a link and step guide please ?

**Comment by shiraishi-png** [comment]
> > A clean install of ReForge worked for me flawlessly on windows, it automatically downloads the nightly cu128 version for windows.
> 
> Can you post a link and step guide please ?

https://github.com/[Panchovix/stable-diffusion-webui-reForge](https://github.com/Panchovix/stable-diffusion-webui-reForge)

Follow the install instructions (Clean install), that's all I had to do for it to work

**Comment by allerias** [comment]
Reforge works after a fresh install but it's not Forge

**Comment by shiraishi-png** [comment]
> Reforge works after a fresh install but it's not Forge

Correct. Therefore, if your solution of copying the venv from ReForge into Forge works, then in my opinion it still applies to help @Natural-Warp to install ReForge, since they will need to be able to install it to apply the solution.

**Comment by guiteubeuh** [comment]
> I can run forge again after do the following easy steps:
> 
>     * Perform a fresh install of ReForge (https://github.com/Panchovix/stable-diffusion-webui-reForge)
> 
>     * Remove Forge venv folder
> 
>     * Copy the venv folder of Reforge into the Forge directory

Where is the 'venv' FORGE folder located? I can't find it anywhere. (Windows)

**Comment by killua132445** [comment]
> > I can run forge again after do the following easy steps:
> > ```
> > * Perform a fresh install of ReForge (https://github.com/Panchovix/stable-diffusion-webui-reForge)
> > 
> > * Remove Forge venv folder
> > 
> > * Copy the venv folder of Reforge into the Forge directory
> > ```
> 
> Where is the 'venv' FORGE folder located? I can't find it anywhere. (Windows)

For me it's in (stable-diffusion-forge main folder)/webui/venv. Let me know if it works for you since I got to run the ssd reforge but i'm getting the same cuda kernel error on forge.

**Comment by guiteubeuh** [comment]
After activating the virtual environment and installing PyTorch and torchvision for my Python version, my forge works as intended.

> > > I can run forge again after do the following easy steps:
> > > ```
> > > * Perform a fresh install of ReForge (https://github.com/Panchovix/stable-diffusion-webui-reForge)
> > > 
> > > * Remove Forge venv folder
> > > 
> > > * Copy the venv folder of Reforge into the Forge directory
> > > ```
> > 
> > 
> > Where is the 'venv' FORGE folder located? I can't find it anywhere. (Windows)
> 
> For me it's in (stable-diffusion-forge main folder)/webui/venv. Let me know if it works for you since I got to run the ssd reforge but i'm getting the same cuda kernel error on forge.

Thank you !
After activating the virtual environment and installing PyTorch and Torchvision for my Python version (inside the venv), my forge works as intended with my 5080.

**Comment by Zedrath** [comment]
> After activating the virtual environment and installing PyTorch and torchvision for my Python version, my forge works as intended.
> 
> > > > I can run forge again after do the following easy steps:
> > > > ```
> > > > * Perform a fresh install of ReForge (https://github.com/Panchovix/stable-diffusion-webui-reForge)
> > > > 
> > > > * Remove Forge venv folder
> > > > 
> > > > * Copy the venv folder of Reforge into the Forge directory
> > > > ```
> > > 
> > > 
> > > Where is the 'venv' FORGE folder located? I can't find it anywhere. (Windows)
> > 
> > 
> > For me it's in (stable-diffusion-forge main folder)/webui/venv. Let me know if it works for you since I got to run the ssd reforge but i'm getting the same cuda kernel error on forge.
> 
> Thank you ! After activating the virtual environment and installing PyTorch and Torchvision for my Python version (inside the venv), my forge works as intended with my 5080.

Have you encountered any GPU crashing with permanent black screens and the only way to solve it is to restart the computer? 

I seem to get it with certain checkpoints or if i batch 10+ generations.

**Comment by zzeshz** [comment]
> > > I can run forge again after do the following easy steps:
> > > ```
> > > * Perform a fresh install of ReForge (https://github.com/Panchovix/stable-diffusion-webui-reForge)
> > > 
> > > * Remove Forge venv folder
> > > 
> > > * Copy the venv folder of Reforge into the Forge directory
> > > ```
> > 
> > 
> > Where is the 'venv' FORGE folder located? I can't find it anywhere. (Windows)
> 
> For me it's in (stable-diffusion-forge main folder)/webui/venv. Let me know if it works for you since I got to run the ssd reforge but i'm getting the same cuda kernel error on forge.

Tried this out, seems to still throw me the same "no kernel image is available for execution on the device" as well. Probably missing something, but i'm pretty stumped.

**Comment by zzeshz** [comment]
> It's working now fully, just install PyTorch and Torchvision for the version of Python you are running (Likely 3.10) from here https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv You will then have to use the latest bitsandbytes version from here for blackwell GPUs https://github.com/bitsandbytes-foundation/bitsandbytes/releases
> 
> In StabilityMatrix this can be done by right clicking the forge install, going to "Python Packages" and clicking the "+" icon on the top left. Just copy/paste the link for PyTorch so it says PIP INSTALL URLHERE hit enter, do this for Torchvision also and if needed bitsandbytes. Make sure they are selected from the same "Python Packages" window. Your forge will not work without errors.
> 
> You might get an error about "libbitsandbytes_cuda128" not found. Just track the file down and place it in folder it says its missing from manually and it will go away.
> 
> Hope this helps folks, i just got it up and running on my 5070 ti doing the above without issues. Just remember the PyTorch and Torchvision your going to be using is not final check for updates every now and then until the official ones come out.

Using StabilityMatrix worked out for me, I must've been screwing something up when trying manually. Thank you!

**Comment by EpicMulletGuy** [comment]
> > It's working now fully, just install PyTorch and Torchvision for the version of Python you are running (Likely 3.10) from here https://huggingface.co/w-e-w/torch-2.6.0-cu128.nv You will then have to use the latest bitsandbytes version from here for blackwell GPUs https://github.com/bitsandbytes-foundation/bitsandbytes/releases
> > In StabilityMatrix this can be done by right clicking the forge install, going to "Python Packages" and clicking the "+" icon on the top left. Just copy/paste the link for PyTorch so it says PIP INSTALL URLHERE hit enter, do this for Torchvision also and if needed bitsandbytes. Make sure they are selected from the same "Python Packages" window. Your forge will not work without errors.
> > You might get an error about "libbitsandbytes_cuda128" not found. Just track the file down and place it in folder it says its missing from manually and it will go away.
> > Hope this helps folks, i just got it up and running on my 5070 ti doing the above without issues. Just remember the PyTorch and Torchvision your going to be using is not final check for updates every now and then until the official ones come out.
> 
> Using StabilityMatrix worked out for me, I must've been screwing something up when trying manually. Thank you!

No problem, to manually do it you need to enter the environment folder and do it through a CLI.  Just remember when forge updates your likely need to do this again until something official comes out.

**Comment by zebulon2** [comment]
> I am getting the same error, does anyone have any fixes? EDIT: fixed it by downgrading triton version to 3.1.0
> 
> Another issue I have run into: WARNING:bitsandbytes.cextension:Could not find the bitsandbytes CUDA binary at PosixPath('/home/victor/stable-diffusion-webui-forge/venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cuda128.so') WARNING:bitsandbytes.cextension:The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
> 
> Any ideas?

Many thanks triton 3.1 fixed the issue. I see the same bitsandbytes warning but it does not impact use. I do not know if it would impact quality of interpretation of the prompts though.

**Comment by EpicMulletGuy** [comment]
> > I am getting the same error, does anyone have any fixes? EDIT: fixed it by downgrading triton version to 3.1.0
> > Another issue I have run into: WARNING:bitsandbytes.cextension:Could not find the bitsandbytes CUDA binary at PosixPath('/home/victor/stable-diffusion-webui-forge/venv/lib/python3.12/site-packages/bitsandbytes/libbitsandbytes_cuda128.so') WARNING:bitsandbytes.cextension:The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
> > Any ideas?
> 
> Many thanks triton 3.1 fixed the issue. I see the same bitsandbytes warning but it does not impact use. I do not know if it would impact quality of interpretation of the prompts though.

Copy the missing DLL file "libbitsandbytes_cuda128" (it should be) to the X\Stable Diffusion WebUI Forge\venv\Lib\site-packages\bitsandbytes folder and restart. If you have comfyui or something else installed you can just do a search for it then copy/paste it into the forge folder location as above. Then the warning will go away.

**Comment by reaperhammer** [comment]
In the end I figured out my Forge was not using any venv and rather it was just using the custom python.exe location, so I was able to upgrade torch and torchvision like this, in cmd;

`cd F:\GithubClones\Forge\system\python
F:
.\python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
.\python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cu128
`

Can't remember if I also had to upgrade bitsandbytes for forge or if that was another project... 
if you did need to upgrade it;

.\python.exe -s -m pip install --pre --upgrade --no-cache-dir bitsandbytes

**Comment by AlargerCorgi** [comment]
Does anyone have exact steps to get Forge SD working with cu128 on Windows? Like what commands do we need to run from git clone to copy and pasting the bitsandbytes from ComfyUI?

**Comment by kontinyu** [comment]
> Does anyone have exact steps to get Forge SD working with cu128 on Windows? Like what commands do we need to run from git clone to copy and pasting the bitsandbytes from ComfyUI?

I did it by going to,
C:\pinokio\api\stable-diffusion-webui-forge.git\app\venv\Scripts
Start "cmd" in the folder.
Run:

pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

After that it works with pinokio installation of Forge. should be similiar for the standalone too.

**Comment by kentstone84** [comment]
✅ [FIXED] Full RTX 5080 / sm_120 Support Working — Custom Patch Repo

After weeks of digging, reverse engineering, failed builds, and driver analysis, I’ve successfully enabled full sm_120 (Blackwell architecture) support on the RTX 5080 locally in PyTorch — without waiting for NVIDIA or nightly builds.

🔍 What Was Really Going On:
NVIDIA’s libcuda.so explicitly blocks sm_120 via an internal architecture check — not a hardware limitation, but a deliberate software lock. This is why PyTorch would compile successfully for compute_120, but fail at runtime.

🛠️ What I Did:
Reverse engineered libcuda.so with Ghidra.

Patched the status byte in the architecture validation logic.

Injected a runtime shim to override cuDeviceGetAttribute behavior.

Rebuilt PyTorch from source with TORCH_CUDA_ARCH_LIST="Blackwell".

🔗 Repo:  https://github.com/kentstone84/pytorch-rtx5080-support.git

Includes:

patch_blackwell.sh for PyTorch build system

Binary patch diff

CUDA shim source (optional)

Full build instructions

This completely resolves the PyTorch + RTX 5080 compatibility issue on Linux.

💬 Maintainers: You can mark this as solved. If anyone needs help applying this or wants to collaborate on wider Blackwell support, feel free to fork or open an issue on the repo.

– The Architect

**Comment by zlo899nv** [comment]
Hi all!  Update from our NVIDIA team.

To use PyTorch for Windows on NVIDIA 5080, 5090 Blackwell RTX GPUs use the latest nightly builds, or the command below.

pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

Let us know if you have any questions, Thanks!

**Comment by kentstone84** [comment]
@zlo899nv Appreciate the update, but let’s be clear — the nightly cu128 wheels don’t solve the actual problem.

Your response completely sidesteps the core issue:
The official PyTorch binaries still fail to execute on RTX 5080 without sm_120 support being force-enabled. I didn’t wait around for a patch — I made one. From the ground up.

While you point to a future workaround, I reverse-engineered the driver, identified the blocked architecture validation in libcuda.so.1.1, and rewired the logic manually. My solution doesn’t depend on waiting for corporate approval — it unlocks the hardware NVIDIA actively restricts.

You're welcome to use the patch, by the way. It's open-source.
But don’t act like a pip command was all it took.
It wasn't.

– The Architect

**Comment by kentstone84** [comment]
![Screenshot 2025-03-23 122642.png](https://github.com/user-attachments/assets/8fcb9fb3-b83a-4dae-b181-e6badc2fdbbc)

What happens when you don't nightly build and activate Nvidia architecture. ![Screenshot_20250323_124616_ChatGPT.jpg](https://github.com/user-attachments/assets/f38efb7f-c4d4-45fe-b33d-dcc0fe3715cc)

**Comment by zlo899nv** [comment]
> [@zlo899nv](https://github.com/zlo899nv) Appreciate the update, but let’s be clear — the nightly cu128 wheels don’t solve the actual problem.
> 
> Your response completely sidesteps the core issue: The official PyTorch binaries still fail to execute on RTX 5080 without sm_120 support being force-enabled. I didn’t wait around for a patch — I made one. From the ground up.
> 
> While you point to a future workaround, I reverse-engineered the driver, identified the blocked architecture validation in libcuda.so.1.1, and rewired the logic manually. My solution doesn’t depend on waiting for corporate approval — it unlocks the hardware NVIDIA actively restricts.
> 
> You're welcome to use the patch, by the way. It's open-source. But don’t act like a pip command was all it took. It wasn't.
> 
> – The Architect

Hi @kentstone84,

Thank you and appreciate your community contributions.  In no way was it meant to seem like the pip command was the solution.  I'll share your contributions with the team.

**Comment by kentstone84** [comment]
Hey @zlo899nv — appreciate the reply and that you're passing this up the chain. Since you're sharing it with the team, let me lay it out clearly so there’s no confusion on what’s actually going on and what can be done.

This isn’t a PyTorch problem. The core issue is in the driver — libcuda.so.1.1 is actively rejecting sm_120, which blocks RTX 5080 and 5090 cards no matter what you do at the framework level.

I reversed the binary and found the exact failure point inside FUN_005d69a0 where the logic sets:

local_39 = 0x2c;
That’s the line that throws the arch rejection. That’s not a missing feature — that’s a hardcoded block.

Here’s what the team can do if they actually want to fix it:

Remove the sm_120 rejection from libcuda.so.1.1.
Stop forcing local_39 = 0x2c and instead let the driver validate against actual hardware capability. This shouldn't be hard.

Add sm_120 to the CUDA toolkit.
Put it in CUDA_ARCH_BIN and CUDA_ARCH_PTX lists so people can compile kernels, extensions, and Torch backends without patching build scripts.

Make it clear in the changelog that Blackwell support is in progress.
Just a line saying “sm_120 experimental support enabled” would save devs a lot of time and stop people from hunting offsets in hex editors.

If you really don’t want to commit to full support yet, at least expose a flag like:

export NVIDIA_ALLOW_UNSUPPORTED_ARCHS=true
Most devs are fine with flipping a switch as long as you give us the option.

Last thing — this ain’t about performance. It’s about permission. I didn’t wait around for a fix, I made one. I just want the hardware I bought to actually run code without getting blocked by artificial locks.

If someone on the driver team wants to talk, I'm down. Otherwise, this is all open-source. Anyone’s free to use it.

– The Architect
https://github.com/kentstone84/pytorch-rtx5080-support

**Comment by Natural-Warp** [comment]
> ✅ [FIXED] Full RTX 5080 / sm_120 Support Working — Custom Patch Repo
> 
> After weeks of digging, reverse engineering, failed builds, and driver analysis, I’ve successfully enabled full sm_120 (Blackwell architecture) support on the RTX 5080 locally in PyTorch — without waiting for NVIDIA or nightly builds.
> 
> 🔍 What Was Really Going On: NVIDIA’s libcuda.so explicitly blocks sm_120 via an internal architecture check — not a hardware limitation, but a deliberate software lock. This is why PyTorch would compile successfully for compute_120, but fail at runtime.
> 
> 🛠️ What I Did: Reverse engineered libcuda.so with Ghidra.
> 
> Patched the status byte in the architecture validation logic.
> 
> Injected a runtime shim to override cuDeviceGetAttribute behavior.
> 
> Rebuilt PyTorch from source with TORCH_CUDA_ARCH_LIST="Blackwell".
> 
> 🔗 Repo: https://github.com/kentstone84/pytorch-rtx5080-support.git
> 
> Includes:
> 
> patch_blackwell.sh for PyTorch build system
> 
> Binary patch diff
> 
> CUDA shim source (optional)
> 
> Full build instructions
> 
> This completely resolves the PyTorch + RTX 5080 compatibility issue on Linux.
> 
> 💬 Maintainers: You can mark this as solved. If anyone needs help applying this or wants to collaborate on wider Blackwell support, feel free to fork or open an issue on the repo.
> 
> – The Architect

So does this work for window<s 11 or linux only ?

**Comment by kentstone84** [comment]
> > ✅ [FIXED] Full RTX 5080 / sm_120 Support Working — Custom Patch Repo
> > 
> > After weeks of digging, reverse engineering, failed builds, and driver analysis, I’ve successfully enabled full sm_120 (Blackwell architecture) support on the RTX 5080 locally in PyTorch — without waiting for NVIDIA or nightly builds.
> > 
> > 🔍 What Was Really Going On: NVIDIA’s libcuda.so explicitly blocks sm_120 via an internal architecture check — not a hardware limitation, but a deliberate software lock. This is why PyTorch would compile successfully for compute_120, but fail at runtime.
> > 
> > 🛠️ What I Did: Reverse engineered libcuda.so with Ghidra.
> > 
> > Patched the status byte in the architecture validation logic.
> > 
> > Injected a runtime shim to override cuDeviceGetAttribute behavior.
> > 
> > Rebuilt PyTorch from source with TORCH_CUDA_ARCH_LIST="Blackwell".
> > 
> > 🔗 Repo: https://github.com/kentstone84/pytorch-rtx5080-support.git
> > 
> > Includes:
> > 
> > patch_blackwell.sh for PyTorch build system
> > 
> > Binary patch diff
> > 
> > CUDA shim source (optional)
> > 
> > Full build instructions
> > 
> > This completely resolves the PyTorch + RTX 5080 compatibility issue on Linux.
> > 
> > 💬 Maintainers: You can mark this as solved. If anyone needs help applying this or wants to collaborate on wider Blackwell support, feel free to fork or open an issue on the repo.
> > 
> > – The Architect
> 
> So does this work for window<s 11 or linux only ?

Yes — the patch works on both Windows 11 and Linux, but with some caveats:

Linux:

Fully working with the patched libcuda.so shim.

Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.

I've validated full functionality including matmuls, inference, and OpenCL benchmarks.

You can preload the shim with:

LD_PRELOAD=./libcuda_shim.so python3


Windows 11:

Works via DLL override method, but slightly trickier due to signed driver limitations.

You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).

PyTorch will still require a local build with Blackwell (sm_120) enabled.

I recommend Linux for ease of testing — but Windows is absolutely possible.

**Comment by Natural-Warp** [comment]
> Yes — the patch works on both Windows 11 and Linux, but with some caveats:
> 
> Linux:
> 
> Fully working with the patched libcuda.so shim.
> 
> Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.
> 
> I've validated full functionality including matmuls, inference, and OpenCL benchmarks.
> 
> You can preload the shim with:
> 
> LD_PRELOAD=./libcuda_shim.so python3
> 
> Windows 11:
> 
> Works via DLL override method, but slightly trickier due to signed driver limitations.
> 
> You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).
> 
> PyTorch will still require a local build with Blackwell (sm_120) enabled.
> 
> I recommend Linux for ease of testing — but Windows is absolutely possible.

Thanks for this, I'm hoping to run SD ForgeUI Flux with my 5080.
But must admit all of this goes way above my head and unless there's a clear how to / step by step, I'm completely lost.

**Comment by alibakhtiari2** [comment]
> > > Yes — the patch works on both Windows 11 and Linux, but with some caveats:
> > > Linux:
> > > Fully working with the patched libcuda.so shim.
> > > Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.
> > > I've validated full functionality including matmuls, inference, and OpenCL benchmarks.
> > > You can preload the shim with:
> > > LD_PRELOAD=./libcuda_shim.so python3
> > > Windows 11:
> > > Works via DLL override method, but slightly trickier due to signed driver limitations.
> > > You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).
> > > PyTorch will still require a local build with Blackwell (sm_120) enabled.
> > > I recommend Linux for ease of testing — but Windows is absolutely possible.
> > 
> > 
> > Thanks for this, I'm hoping to run SD ForgeUI Flux with my 5080.
> > But must admit all of this goes way above my head and unless there's a clear how to / step by step, I'm completely lost.
> 
> No worries — I get it. NVIDIA didn’t make this easy on purpose.
> 
> I’m working on putting together a step-by-step guide specifically for folks in your spot: just want SD ForgeUI (or anything else using PyTorch) to run properly on the 5080 without needing a CS degree or Ghidra.
> 
> For now, if you just want it to work without diving into reverse-engineering:
> 
> 1. Install Python 3.10 or 3.11
> 2. Create a fresh virtual environment
> 
> python -m venv venv source venv/bin/activate # or .\venv\Scripts\activate on Windows
> 
> 3. Install the nightly PyTorch build with CUDA 12.8 (this is NVIDIA’s workaround for now)
> 
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> 4. Then try launching SD ForgeUI Flux and see if it detects your GPU.
> 
> That’ll get you running, even if it doesn’t fix the deeper problem.
> 
> If you want full unlocked access to the 5080’s real compute power without waiting on NVIDIA, I’ve got a patch up that replaces the driver-level lock. It’s not hard to apply, but yeah — I’ll make a walkthrough for that soon too.
> 
> Hang tight. You’re not alone.
> 
> – The Architect

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> > Yes — the patch works on both Windows 11 and Linux, but with some caveats:
> > Linux:
> > Fully working with the patched libcuda.so shim.
> > Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.
> > I've validated full functionality including matmuls, inference, and OpenCL benchmarks.
> > You can preload the shim with:
> > LD_PRELOAD=./libcuda_shim.so python3
> > Windows 11:
> > Works via DLL override method, but slightly trickier due to signed driver limitations.
> > You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).
> > PyTorch will still require a local build with Blackwell (sm_120) enabled.
> > I recommend Linux for ease of testing — but Windows is absolutely possible.
> 
> Thanks for this, I'm hoping to run SD ForgeUI Flux with my 5080. But must admit all of this goes way above my head and unless there's a clear how to / step by step, I'm completely lost.

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> > > Yes — the patch works on both Windows 11 and Linux, but with some caveats:
> > > Linux:
> > > Fully working with the patched libcuda.so shim.
> > > Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.
> > > I've validated full functionality including matmuls, inference, and OpenCL benchmarks.
> > > You can preload the shim with:
> > > LD_PRELOAD=./libcuda_shim.so python3
> > > Windows 11:
> > > Works via DLL override method, but slightly trickier due to signed driver limitations.
> > > You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).
> > > PyTorch will still require a local build with Blackwell (sm_120) enabled.
> > > I recommend Linux for ease of testing — but Windows is absolutely possible.
> > 
> > 
> > Thanks for this, I'm hoping to run SD ForgeUI Flux with my 5080.
> > But must admit all of this goes way above my head and unless there's a clear how to / step by step, I'm completely lost.
> 
> No worries — I get it. NVIDIA didn’t make this easy on purpose.
> 
> I’m working on putting together a step-by-step guide specifically for folks in your spot: just want SD ForgeUI (or anything else using PyTorch) to run properly on the 5080 without needing a CS degree or Ghidra.
> 
> For now, if you just want it to work without diving into reverse-engineering:
> 
> 1. Install Python 3.10 or 3.11
> 2. Create a fresh virtual environment
> 
> python -m venv venv source venv/bin/activate # or .\venv\Scripts\activate on Windows
> 
> 3. Install the nightly PyTorch build with CUDA 12.8 (this is NVIDIA’s workaround for now)
> 
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> 4. Then try launching SD ForgeUI Flux and see if it detects your GPU.
> 
> That’ll get you running, even if it doesn’t fix the deeper problem.
> 
> If you want full unlocked access to the 5080’s real compute power without waiting on NVIDIA, I’ve got a patch up that replaces the driver-level lock. It’s not hard to apply, but yeah — I’ll make a walkthrough for that soon too.
> 
> Hang tight. You’re not alone.
> 
> – The Architect

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> > ✅ [FIXED] Full RTX 5080 / sm_120 Support Working — Custom Patch Repo
> > After weeks of digging, reverse engineering, failed builds, and driver analysis, I’ve successfully enabled full sm_120 (Blackwell architecture) support on the RTX 5080 locally in PyTorch — without waiting for NVIDIA or nightly builds.
> > 🔍 What Was Really Going On: NVIDIA’s libcuda.so explicitly blocks sm_120 via an internal architecture check — not a hardware limitation, but a deliberate software lock. This is why PyTorch would compile successfully for compute_120, but fail at runtime.
> > 🛠️ What I Did: Reverse engineered libcuda.so with Ghidra.
> > Patched the status byte in the architecture validation logic.
> > Injected a runtime shim to override cuDeviceGetAttribute behavior.
> > Rebuilt PyTorch from source with TORCH_CUDA_ARCH_LIST="Blackwell".
> > 🔗 Repo: https://github.com/kentstone84/pytorch-rtx5080-support.git
> > Includes:
> > patch_blackwell.sh for PyTorch build system
> > Binary patch diff
> > CUDA shim source (optional)
> > Full build instructions
> > This completely resolves the PyTorch + RTX 5080 compatibility issue on Linux.
> > 💬 Maintainers: You can mark this as solved. If anyone needs help applying this or wants to collaborate on wider Blackwell support, feel free to fork or open an issue on the repo.
> > – The Architect
> 
> So does this work for window<s 11 or linux only ?

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90. If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
> 
> This message appears when starting up and generation is no longer possible. In other words, since the new GPU RTX5080 does not support CUDA121, I think it is necessary to rebuild the venv with a new version of CUDA. (For example, CUDA126?)
> 
> However, when trying to build a venv from user.bat, the file is forcibly built for the CUDA121 environment, which is inconsistent with CUDA126 and makes it impossible to even install. Can someone please tell me how to solve this?
> 
> It may be a problem with the RTX5080 driver...

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> Same issue with RTX5090

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> > Nvidia spamming that AI AI AI AI everywhere but they cant communicate with real AI programmists to release their card and drivers all compatible with all environements. This should be highlighted everywhere, and people responsible for the lack of support on day 3 of release of that cards should be fired! Or nvidia to just drop so low on stock values that would send them forever to polish AMD shoes. Not to mention that they released DLSS 4 but only people that know how to correctly install them to games can enjoy the transformer model of dlss. This is really a circus and literally worst release ever of their cards. I was lucky to grab 5080 but i really want right now to sell it so i can forget about headache configuring of that card gave me already.
> 
> nobody's gonna communicate anything, there are too many caveats, everyone with their own affairs and schedule. Just wait a week or two, new pytorch pip should drop soon.

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> same with 5080 comfy ui

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> NVIDIA GeForce RTX 5080 with CUDA capability sm_120 is not compatible with the current PyTorch installation. The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90. If you want to use the NVIDIA GeForce RTX 5080 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/
> 
> This message appears when starting up and generation is no longer possible. In other words, since the new GPU RTX5080 does not support CUDA121, I think it is necessary to rebuild the venv with a new version of CUDA. (For example, CUDA126?)
> 
> However, when trying to build a venv from user.bat, the file is forcibly built for the CUDA121 environment, which is inconsistent with CUDA126 and makes it impossible to even install. Can someone please tell me how to solve this?
> 
> It may be a problem with the RTX5080 driver...

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by alibakhtiari2** [comment]
> > Yes — the patch works on both Windows 11 and Linux, but with some caveats:
> > Linux:
> > Fully working with the patched libcuda.so shim.
> > Requires rebuilding PyTorch from source with the patch applied and TORCH_CUDA_ARCH_LIST="Blackwell" set.
> > I've validated full functionality including matmuls, inference, and OpenCL benchmarks.
> > You can preload the shim with:
> > LD_PRELOAD=./libcuda_shim.so python3
> > Windows 11:
> > Works via DLL override method, but slightly trickier due to signed driver limitations.
> > You can patch the driver in-memory (e.g., using an injected shim or runtime DLL redirect).
> > PyTorch will still require a local build with Blackwell (sm_120) enabled.
> > I recommend Linux for ease of testing — but Windows is absolutely possible.
> 
> Thanks for this, I'm hoping to run SD ForgeUI Flux with my 5080. But must admit all of this goes way above my head and unless there's a clear how to / step by step, I'm completely lost.

Hi

I fixed the issue. visit my page. https://github.com/alibakhtiari2/fooocusrtx508090

i fixed the dependencies. now its running on rtx 50 series.

please share

**Comment by kris3890** [comment]
> In the end I figured out my Forge was not using any venv and rather it was just using the custom python.exe location, so I was able to upgrade torch and torchvision like this, in cmd;
> 
>     * chdir /d F:\GithubClones\Forge\system\python
> 
>     * .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
> 
>     * .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cu128
> 
> 
> Can't remember if I also had to upgrade bitsandbytes for forge or if that was another project... if you did need to upgrade it;
> 
> .\python.exe -s -m pip install --pre --upgrade --no-cache-dir bitsandbytes

THIS IS THE FIX!!!!!

THANK YOU SO MUCH MAN! I HAVE BEEN SEARCHING FOR AN ACTUAL FIX FOR 2 WEEKS. 
Ignore the indian guy spamming his own WebUI lol.

**Comment by kris3890** [comment]
> In the end I figured out my Forge was not using any venv and rather it was just using the custom python.exe location, so I was able to upgrade torch and torchvision like this, in cmd;
> 
>     * chdir /d F:\GithubClones\Forge\system\python
> 
>     * .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/nightly/cu128
> 
>     * .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/nightly/cu128
> 
> 
> Can't remember if I also had to upgrade bitsandbytes for forge or if that was another project... if you did need to upgrade it;
> 
> .\python.exe -s -m pip install --pre --upgrade --no-cache-dir bitsandbytes

THIS IS THE FIX!!! THANK YOU SO MUCH @reaperhammer !!!!

**Comment by kentstone84** [comment]
I can 100% tell you that is not the fix. If you go inside the night the sm_120 architecture for the 50 series GPUs is passed over using a pass flag. Go in a look. The only true was is the remove the softlock to the sm120 architecture found inside libcuda.so.1.1

**Comment by alibakhtiari2** [comment]
> I can 100% tell you that is not the fix. If you go inside the night the sm_120 architecture for the 50 series GPUs is passed over using a pass flag. Go in a look. The only true was is the remove the softlock to the sm120 architecture found inside libcuda.so.1.1
 buddy this is the fix:D 100% gurantee

**Comment by kris3890** [comment]
> I can 100% tell you that is not the fix. If you go inside the night the sm_120 architecture for the 50 series GPUs is passed over using a pass flag. Go in a look. The only true was is the remove the softlock to the sm120 architecture found inside libcuda.so.1.1

but it works now? lol

**Comment by alibakhtiari2** [comment]
Buddy. I’m a different person. 4 weeks ago I reached a solution for it and
I published it into my GitHub account and my server. So many people
download and run it with no any issue.
Try my link and leave a review.  Thanks

https://www.github.com/alibakhtiari2

Ali Bakhtiari
*E-Mail: ***@***.***

**Comment by kentstone84** [comment]
![Screenshot 2025-03-25 201806.png](https://github.com/user-attachments/assets/fa724814-2735-40ce-a893-d0c59deb0392)

Compare yours to mine.

**Comment by kentstone84** [comment]
So what's the deal you are actually about 10k points lower right?! Yeah I know it's funny like that. Maybe I can tell you how to fix it but your GitHub and your server must be doing good. I have one of the most viewed profiles on LinkedIn. I meet with Nvidia executives because they ask me for a meeting. Thanks for trying.

**Comment by kris3890** [comment]
wth did this issue thread turn into lmao

**Comment by Tyrannius** [comment]
> Hey [@zlo899nv](https://github.com/zlo899nv) — appreciate the reply and that you're passing this up the chain. Since you're sharing it with the team, let me lay it out clearly so there’s no confusion on what’s actually going on and what can be done.
> 
> This isn’t a PyTorch problem. The core issue is in the driver — libcuda.so.1.1 is actively rejecting sm_120, which blocks RTX 5080 and 5090 cards no matter what you do at the framework level.
> 
> I reversed the binary and found the exact failure point inside FUN_005d69a0 where the logic sets:
> 
> local_39 = 0x2c; That’s the line that throws the arch rejection. That’s not a missing feature — that’s a hardcoded block.
> 
> Here’s what the team can do if they actually want to fix it:
> 
> Remove the sm_120 rejection from libcuda.so.1.1. Stop forcing local_39 = 0x2c and instead let the driver validate against actual hardware capability. This shouldn't be hard.
> 
> Add sm_120 to the CUDA toolkit. Put it in CUDA_ARCH_BIN and CUDA_ARCH_PTX lists so people can compile kernels, extensions, and Torch backends without patching build scripts.
> 
> Make it clear in the changelog that Blackwell support is in progress. Just a line saying “sm_120 experimental support enabled” would save devs a lot of time and stop people from hunting offsets in hex editors.
> 
> If you really don’t want to commit to full support yet, at least expose a flag like:
> 
> export NVIDIA_ALLOW_UNSUPPORTED_ARCHS=true Most devs are fine with flipping a switch as long as you give us the option.
> 
> Last thing — this ain’t about performance. It’s about permission. I didn’t wait around for a fix, I made one. I just want the hardware I bought to actually run code without getting blocked by artificial locks.
> 
> If someone on the driver team wants to talk, I'm down. Otherwise, this is all open-source. Anyone’s free to use it.
> 
> – The Architect https://github.com/kentstone84/pytorch-rtx5080-support


I dont understand, why they would do that... Like they know people cant create those cuda kernels despite having bought a rtx5080 and pytorch actually supporting it? 
Trying to build with 2.6.0 , no luck. I checked the bash of the patch:  list(APPEND TORCH_CUDA_ARCH_LIST isnt found in the cuda.cmake file (supposedly at line 200) 
Trying now with 2.5.0
Did you specifically test it on 2.5.0?

**Comment by chreepha** [comment]
you are not giving enough info to make patch on windows,

**Comment by chreepha** [comment]
my version sat cuda1,29 on a 5080

**Comment by chreepha** [comment]
i dont know if i have to uninstall everything related to cuda, python version 10.6

**Comment by kentstone84** [comment]
The new cuda unlock is not irrielevel t I'm making a custom driver that
bypasses all of their blocks for the driver level it is a entire new driver
not made by Nvidia but by using their parts I was able to make a very very
very fast replica so very soon everybody be able to start downloading the
upgrade

**Comment by kentstone84** [comment]
So I was attending the CIAt University and with all this shit went down and they automatically expelled me with no email communication of any type I had notified them at the beginning of the term that I was in the hospital preparing for surgery and then the VA also automatically took back $260 at housing is that right for the VA to do that

**Comment by kentstone84** [comment]
So I was attending the CIAt University and with all this shit went down and they automatically expelled me with no email communication of any type I had notified them at the beginning of the term that I was in the hospital preparing for surgery and then the VA also automatically took back $260 at housing is that right for the VA to do that

**Comment by chreepha** [comment]
thanks man, I'm using a version of stable-diffusion-webui-reForge , its very poor quality imaging and not configure able, 
i hope its not to difficult to install thanks for working on what should never have happened,

**Comment by kentstone84** [comment]
Okay if you people want the 5080 release that showed 300ftps ok ultra
flight time and the. Please give me q week to get home be cause of
hospital.. check give me some time and I'll send it
Kent Stone
F Nvidia in the porker.

**Comment by kentstone84** [comment]
You could switch to pytorch but they still haven't figured their chit out.

**Comment by chreepha** [comment]
> Okay if you people want the 5080 release that showed 300ftps ok ultra
> flight time and the. Please give me q week to get home be cause of
> hospital.. check give me some time and I'll send it
> Kent Stone
> F Nvidia in the porker.
so i say thanks for working on this problem, and please make i somewhat understandable for us NB's
I'm using a somewhat hashed version of reforge and images suck,

**Comment by chreepha** [comment]
Oh by the way? i hope the hospital thing is not you?

**Comment by kentstone84** [comment]
I wish that too
Kent Stone

**Comment by starlitxiling** [comment]
> > Hey [@zlo899nv](https://github.com/zlo899nv) — appreciate the reply and that you're passing this up the chain. Since you're sharing it with the team, let me lay it out clearly so there’s no confusion on what’s actually going on and what can be done.嘿 [，@zlo899nv](https://github.com/zlo899nv) — 感谢您的回复，以及您将此消息传递到链条上。既然你要与团队分享它，就让我清楚地列出来，这样就不会对实际发生的事情和可以做什么产生混淆。
> > This isn’t a PyTorch problem. The core issue is in the driver — libcuda.so.1.1 is actively rejecting sm_120, which blocks RTX 5080 and 5090 cards no matter what you do at the framework level.这不是 PyTorch 的问题。核心问题在于驱动程序—— libcuda.so.1.1 正在主动拒绝 sm_120，无论你在框架级别做什么，它都会阻止 RTX 5080 和 5090 卡。
> > I reversed the binary and found the exact failure point inside FUN_005d69a0 where the logic sets:我反转了二进制文件，并在 FUN_005d69a0 中找到了逻辑设置的确切故障点：
> > local_39 = 0x2c; That’s the line that throws the arch rejection. That’s not a missing feature — that’s a hardcoded block.local_39 = 0x2c;这就是抛出 Arch 拒绝的线。这不是一个缺失的功能 — 这是一个硬编码的块。
> > Here’s what the team can do if they actually want to fix it:如果团队真的想修复它，他们可以执行以下作：
> > Remove the sm_120 rejection from libcuda.so.1.1. Stop forcing local_39 = 0x2c and instead let the driver validate against actual hardware capability. This shouldn't be hard.从 libcuda.so.1.1 中删除 sm_120 拒绝。停止强制 local_39 = 0x2c，而是让驱动程序根据实际硬件功能进行验证。这应该不难。
> > Add sm_120 to the CUDA toolkit. Put it in CUDA_ARCH_BIN and CUDA_ARCH_PTX lists so people can compile kernels, extensions, and Torch backends without patching build scripts.将 sm_120 添加到 CUDA 工具包中。将其放在 CUDA_ARCH_BIN 和 CUDA_ARCH_PTX 列表中，以便人们可以编译内核、扩展和 Torch 后端，而无需修补构建脚本。
> > Make it clear in the changelog that Blackwell support is in progress. Just a line saying “sm_120 experimental support enabled” would save devs a lot of time and stop people from hunting offsets in hex editors.在更新日志中明确表示 Blackwell 支持正在进行中。只需一行“启用 sm_120 实验性支持”就可以为开发人员节省大量时间，并阻止人们在十六进制编辑器中寻找偏移量。
> > If you really don’t want to commit to full support yet, at least expose a flag like:如果你真的不想承诺完全支持，至少公开一个标志，比如：
> > export NVIDIA_ALLOW_UNSUPPORTED_ARCHS=true Most devs are fine with flipping a switch as long as you give us the option.export NVIDIA_ALLOW_UNSUPPORTED_ARCHS=true 只要您给我们选项，大多数开发人员都可以拨动开关。
> > Last thing — this ain’t about performance. It’s about permission. I didn’t wait around for a fix, I made one. I just want the hardware I bought to actually run code without getting blocked by artificial locks.最后一件事 — 这与性能无关。这是关于许可的。我没有等待修复，我做了一个。我只希望我购买的硬件能够实际运行代码，而不会被人为锁阻塞。
> > If someone on the driver team wants to talk, I'm down. Otherwise, this is all open-source. Anyone’s free to use it.如果车手团队中有人想谈谈，我就沮丧了。否则，这都是开源的。任何人都可以免费使用它。
> > – The Architect https://github.com/kentstone84/pytorch-rtx5080-support– 建筑师 https://github.com/kentstone84/pytorch-rtx5080-support
> 
> I dont understand, why they would do that... Like they know people cant create those cuda kernels despite having bought a rtx5 series while pytorch actually supporting it?我不明白，他们为什么会这样做......就像他们知道人们尽管购买了 rtx5 系列，但无法创建那些 cuda 内核，而 pytorch 实际上支持它？ Trying to build with 2.6.0 , no luck. I checked the bash of the patch: list(APPEND TORCH_CUDA_ARCH_LIST isnt found in the cuda.cmake file (supposedly at line 200)尝试使用 2.6.0 构建，没有运气。我检查了补丁的 bash： list（APPEND TORCH_CUDA_ARCH_LIST 在 cuda.cmake 文件中找不到（据说在第 200 行） Trying now with 2.5.0. Edit: also no APPEND TORCH_CUDA_ARCH_LIST in that cmake file.现在尝试 2.5.0。编辑：该 cmake 文件中也没有 APPEND TORCH_CUDA_ARCH_LIST。
> 
> Did you specifically test it on 2.5.0?您是否专门在 2.5.0 上对其进行了测试？
> 
> I am trying to set TORCH_CUDA_ARCH_LIST=12.0 before building it now...我现在正在尝试在构建之前设置 TORCH_CUDA_ARCH_LIST=12.0...

I have the same problem, have you solved it now?

**Comment by kentstone84** [comment]
🔍 Understanding the Driver-Level Block

Your reverse engineering pinpointed the failure at FUN_005d69a0, where local_39 = 0x2c enforces the rejection of sm_120.  This hardcoded block prevents the driver from recognizing the architecture, effectively sidelining the new RTX 50 series GPUs. 

🛠️ Steps to Address the Issue

1. Modify the Driver Enforcement: Removing the sm_120 rejection from libcuda.so.1.1 is essential.  By stopping the forced local_39 = 0x2c, the driver can validate against actual hardware capabilities. 


2. Update CUDA Toolkit Support: Incorporate sm_120 into the CUDA toolkit by adding it to the CUDA_ARCH_BIN and CUDA_ARCH_PTX lists.  This allows developers to compile kernels and extensions without modifying build scripts. 


3. Enhance Transparency: Clearly state in the changelog that Blackwell support is underway.  A simple line like “sm_120 experimental support enabled” can save developers time and prevent unnecessary troubleshooting. 


4. Introduce an Override Flag: If full support isn't feasible immediately, provide a flag such as export NVIDIA_ALLOW_UNSUPPORTED_ARCHS=true.  This gives developers the autonomy to proceed with their work while acknowledging the experimental nature of the support. 



🔄 Community Workarounds

Developers have been proactive in seeking solutions.  For instance, some have attempted to build TensorFlow from source with CUDA 12.8.0 and cudnn 9.7.0, targeting compute capabilities including sm_120.  However, challenges persist, such as the absence of sm_120 support in certain configurations  .

Similarly, PyTorch users have encountered compatibility warnings when using RTX 5090 GPUs with CUDA capability sm_120.  The current PyTorch installations support up to sm_90, leading to issues unless nightly builds with CUDA 12.8 and Blackwell support are utilized  .

📣 Final Thoughts

The crux of the matter isn't about performance—it's about permission.  Developers are eager to leverage the capabilities of their hardware without being hindered by artificial constraints.  By addressing the driver-level blocks and enhancing transparency, NVIDIA can empower its developer community and foster innovation. 

If the driver team is open to collaboration or discussion, many in the community, including myself, are ready to contribute to a solution. Otherwise, the open-source community will continue to find ways to navigate these challenges.

— The Architect

https://github.com/kentstone84/pytorch-rtx5080-support
