### ISSUE TITLE
RuntimeError: CUDA error with RTX5070tI

### ISSUE THREAD

**Issue by nyancatza** [lllyasviel/stable-diffusion-webui-forge#2721]
I found a solution from some person that said I have to download reForge and copy venv folder and paste it to forge webui folder. 

When i done this. I launch " webui-user.bat file " inside webui folder. I can generate without any error.

But when i launch it with " run.bat " file inside " webui_forge_cu121_torch231 " folder.

It's error with these line :

" RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions. " 

So how to fix this problem. 
Thank you

**Comment by anaganisk** [comment]
ComfyUI has a similar problem https://github.com/comfyanonymous/ComfyUI/discussions/6643
Solution for it was to use 
```sh
.\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
```

**Comment by coolspeed** [comment]
> ComfyUI has a similar problem [comfyanonymous/ComfyUI#6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643) Solution for it was to use
> 
> .\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

This fixed my problem (on Linux).

**Comment by nyancatza** [comment]
> ComfyUI has a similar problem [comfyanonymous/ComfyUI#6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643) Solution for it was to use
> 
> .\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128

It error with these line.

 

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blendmodes 2022 requires numpy<2,>=1.22.1, but you have numpy 2.1.2 which is incompatible.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 11.0.0 which is incompatible.
gradio 4.40.0 requires pillow<11.0,>=8.0, but you have pillow 11.0.0 which is incompatible.
mediapipe 0.10.21 requires numpy<2, but you have numpy 2.1.2 which is incompatible.
mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 3.20.0 which is incompatible.
onnx 1.17.0 requires protobuf>=3.20.2, but you have protobuf 3.20.0 which is incompatible.`

**Comment by coolspeed** [comment]
> > ComfyUI has a similar problem [comfyanonymous/ComfyUI#6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643) Solution for it was to use
> > .\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> 
> It error with these line.
> 
> `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. blendmodes 2022 requires numpy<2,>=1.22.1, but you have numpy 2.1.2 which is incompatible. blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 11.0.0 which is incompatible. gradio 4.40.0 requires pillow<11.0,>=8.0, but you have pillow 11.0.0 which is incompatible. mediapipe 0.10.21 requires numpy<2, but you have numpy 2.1.2 which is incompatible. mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 3.20.0 which is incompatible. onnx 1.17.0 requires protobuf>=3.20.2, but you have protobuf 3.20.0 which is incompatible.`

You have to run these commands:

```
pip install numpy==1.26.2
pip install Pillow==9.5.0
```

**Comment by nyancatza** [comment]
> > > ComfyUI has a similar problem [comfyanonymous/ComfyUI#6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643) Solution for it was to use
> > > .\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> > 
> > 
> > It error with these line.
> > `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. blendmodes 2022 requires numpy<2,>=1.22.1, but you have numpy 2.1.2 which is incompatible. blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 11.0.0 which is incompatible. gradio 4.40.0 requires pillow<11.0,>=8.0, but you have pillow 11.0.0 which is incompatible. mediapipe 0.10.21 requires numpy<2, but you have numpy 2.1.2 which is incompatible. mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 3.20.0 which is incompatible. onnx 1.17.0 requires protobuf>=3.20.2, but you have protobuf 3.20.0 which is incompatible.`
> 
> You need to run the following commands:
> 
> ```
> pip install numpy==1.26.2
> pip install Pillow==9.5.0
> ```

Thank you for  your replied

I've already tried it. Still error with this line below image output at forge Ui. 

`RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`

I'm also very curious why when i launch with " run.bat ". the pytorch version is 2.3.1+cu121 at CMD.

but when i launch with " webui-user.bat ". the pytorch version is 2.7.0.dev20250306+cu128 at CMD without error after generated.

**Comment by Hapseleg** [comment]
> > > > ComfyUI has a similar problem [comfyanonymous/ComfyUI#6643](https://github.com/comfyanonymous/ComfyUI/discussions/6643) Solution for it was to use
> > > > .\python.exe -m pip install  --upgrade --force-reinstall --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu128
> > > 
> > > 
> > > It error with these line.
> > > `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. blendmodes 2022 requires numpy<2,>=1.22.1, but you have numpy 2.1.2 which is incompatible. blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 11.0.0 which is incompatible. gradio 4.40.0 requires pillow<11.0,>=8.0, but you have pillow 11.0.0 which is incompatible. mediapipe 0.10.21 requires numpy<2, but you have numpy 2.1.2 which is incompatible. mediapipe 0.10.21 requires protobuf<5,>=4.25.3, but you have protobuf 3.20.0 which is incompatible. onnx 1.17.0 requires protobuf>=3.20.2, but you have protobuf 3.20.0 which is incompatible.`
> > 
> > 
> > You need to run the following commands:
> > ```
> > pip install numpy==1.26.2
> > pip install Pillow==9.5.0
> > ```
> 
> Thank you for your replied
> 
> I've already tried it. Still error with this line below image output at forge Ui.
> 
> `RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.`
> 
> I'm also very curious why when i launch with " run.bat ". the pytorch version is 2.3.1+cu121 at CMD.
> 
> but when i launch with " webui-user.bat ". the pytorch version is 2.7.0.dev20250306+cu128 at CMD without error after generated.

run.bat vs webui-user.bat difference is that run.bat uses a python venv

**Comment by nyancatza** [comment]
fixed it 

copy " Scripts " folder from " venv " folder and paste at " system\python "
