### ISSUE TITLE
gen works in webui, but torch.cuda.OutOfMemoryError when using API

### ISSUE THREAD

**Issue by Akinetopsia1** [lllyasviel/stable-diffusion-webui-forge#2858]
Albeit slow bc of limited vram, which i don't mind, using flux1-dev gguf running an image gen in the webui works while i get an out of memory error when attempting to run from the API with the same settings.

How can i get the inference to work from the api ? it works with other models.



```
Model selected: {'checkpoint_info': {'filename': '/home/akine/source/stable-diffusion-webui-forge/models/Stable-diffusion/flux1-dev-Q4_K_S.gguf', 'hash': '151c63a2'}, 'additional_modules': ['/home/akine/source/stable-diffusion-webui-forge/models/text_encoder/flux1-dev.safetensors', '/home/akine/source/stable-diffusion-webui-forge/models/text_encoder/sd3.5-t5xxl_fp16.safetensors', '/home/akine/source/stable-diffusion-webui-forge/models/VAE/flux-vae.safetensors'], 'unet_storage_dtype': None}
Using online LoRAs in FP16: False
Loading Model: {'checkpoint_info': {'filename': '/home/akine/source/stable-diffusion-webui-forge/models/Stable-diffusion/flux1-dev-Q4_K_S.gguf', 'hash': '151c63a2'}, 'additional_modules': ['/home/akine/source/stable-diffusion-webui-forge/models/text_encoder/flux1-dev.safetensors', '/home/akine/source/stable-diffusion-webui-forge/models/text_encoder/sd3.5-t5xxl_fp16.safetensors', '/home/akine/source/stable-diffusion-webui-forge/models/VAE/flux-vae.safetensors'], 'unet_storage_dtype': None}
[Unload] Trying to free all memory for cuda:0 with 0 models keep loaded ... Done.
StateDict Keys: {'transformer': 780, 'vae': 244, 'text_encoder': 196, 'text_encoder_2': 220, 'ignore': 0}
Using Default T5 Data Type: torch.float16
Using Detected UNet Type: gguf
Using pre-quant state dict!
GGUF state dict: {'Q4_K': 304}
Working with z of shape (1, 16, 32, 32) = 16384 dimensions.
K-Model Created: {'storage_dtype': 'gguf', 'computation_dtype': torch.bfloat16}
Model loaded in 16.4s (unload existing model: 0.2s, forge model load: 16.2s).
Warning: field infotext in API payload not found in <modules.processing.StableDiffusionProcessingTxt2Img object at 0x737ba0214a90>.
Skipping unconditional conditioning when CFG = 1. Negative Prompts are ignored.
[Unload] Trying to free 13464.34 MB for cuda:0 with 0 models keep loaded ... Done.
[Memory Management] Target: JointTextEncoder, Free GPU: 7220.25 MB, Model Require: 9569.49 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -3373.24 MB, CPU Swap Loaded (blocked method): 4742.00 MB, GPU Loaded: 4899.87 MB
Moving model(s) has taken 5.65 seconds
Distilled CFG Scale: 3.5
[Unload] Trying to free 13598.80 MB for cuda:0 with 0 models keep loaded ... Current free memory is 1774.73 MB ... Unload model JointTextEncoder Done.
[Memory Management] Target: KModel, Free GPU: 7189.83 MB, Model Require: 6490.64 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: -324.81 MB, CPU Swap Loaded (blocked method): 1625.62 MB, GPU Loaded: 4865.02 MB
Moving model(s) has taken 7.96 seconds
  0%|                                                                                                                                                                                                                  | 0/20 [00:00<?, ?it/s]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 724, in __call__
    await self.app(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/akine/source/stable-diffusion-webui-forge/modules/api/api.py", line 495, in text2imgapi
    processed = process_images(p)
  File "/home/akine/source/stable-diffusion-webui-forge/modules/processing.py", line 842, in process_images
    res = process_images_inner(p)
  File "/home/akine/source/stable-diffusion-webui-forge/modules/processing.py", line 990, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "/home/akine/source/stable-diffusion-webui-forge/modules/processing.py", line 1387, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "/home/akine/source/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 238, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/akine/source/stable-diffusion-webui-forge/modules/sd_samplers_common.py", line 278, in launch_sampling
    return func()
  File "/home/akine/source/stable-diffusion-webui-forge/modules/sd_samplers_kdiffusion.py", line 238, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args=self.sampler_extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/k_diffusion/sampling.py", line 129, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/modules/sd_samplers_cfg_denoiser.py", line 199, in forward
    denoised, cond_pred, uncond_pred = sampling_function(self, denoiser_params=denoiser_params, cond_scale=cond_scale, cond_composition=cond_composition)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 362, in sampling_function
    denoised, cond_pred, uncond_pred = sampling_function_inner(model, x, timestep, uncond, cond, cond_scale, model_options, seed, return_full=True)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 303, in sampling_function_inner
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/sampling/sampling_function.py", line 273, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/modules/k_model.py", line 45, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/nn/flux.py", line 418, in forward
    out = self.inner_forward(img, img_ids, context, txt_ids, timestep, y, guidance)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/nn/flux.py", line 389, in inner_forward
    img, txt = block(img=img, txt=txt, vec=vec, pe=pe)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/nn/flux.py", line 247, in forward
    attn = attention(q, k, v, pe=pe)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/nn/flux.py", line 16, in attention
    q, k = apply_rope(q, k, pe)
  File "/home/akine/source/stable-diffusion-webui-forge/backend/nn/flux.py", line 46, in apply_rope
    xq_out = freqs_cis[..., 0] * xq_[..., 0] + freqs_cis[..., 1] * xq_[..., 1]
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 202.00 MiB. GPU 
```

**Comment by Akinetopsia1** [comment]
@MisterChief95 
nvidia 4060 with 8gb vram

gpu weights are at 6906mb in the ui.

Your post actually got me to double check and try yet another tweak and it turns out i was misunderstanding how one of the parameters worked.

when swapping models my current api call options for the flux model were set to: 

`
	"api_forbid_local_requests": false,
	"pin_memory": false,
	"interrogate_keep_models_in_memory": false,
	"forge_inference_memory": 1024.0,      // <- this is the parameter i needed to change 
	"forge_pin_shared_memory": false,
	"forge_async_loading": "Queue",
	"forge_preset": "flux",
`

a quick test and setting it to 4096.0 instead of 1024.0 and it worked! Sounds like this is the equivalent to gpu weights memory in the ui - i assumed it was the difference with the value in that slider.
