### ISSUE TITLE
RTX 5070ti with CUDA capability sm_120 not compatible with the current PyTorch Instalation

### ISSUE THREAD

**Issue by Tony3rd** [lllyasviel/stable-diffusion-webui-forge#3087]
I've just upgraded from a 3070 ti to a 5070 ti. When I load Forge, I'm greeted with the following message:

_NVIDIA GeForce RTX 5070 Ti with CUDA capability sm_120 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_50 sm_60 sm_61 sm_70 sm_75 sm_80 sm_86 sm_90.
If you want to use the NVIDIA GeForce RTX 5070 Ti GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/_

I've installed CUDA 13.1 toolkit. followed the instruction on https://pytorch.org/get-started/locally/ and was able to install the stable version for cuda 12.8 ( pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu128). 

When i try the solution from https://github.com/lllyasviel/stable-diffusion-webui-forge/issues/2746#issuecomment-3263566829 I've get this error message when I try to install the nightly build

_ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch_

So i end up installing the stable one anyway.

What else I can do here to proper config forge to my setup?

Edit: Oh, I'm trying to run on Win 11

**Comment by PsicomonTamer** [comment]
I had the same issue first you must uninstall torch and torch vision 
And run pip cache purge 
then use this command 
In your global python installation 

pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130

Then delete the venv directory of your forge installation and compile it again using update bat
And in the directory venv\scripts run these commands 

.\python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cu130

.\python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/cu130

If first comes with an error just run the second
And rerun the first just to be sure that no errors have occurred
And you should good to go

**Comment by mhj8x** [comment]
> I had the same issue first you must uninstall torch and torch vision And run pip cache purge then use this command In your global python installation
> 
> pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cu130
> 
> Then delete the venv directory of your forge installation and compile it again using update bat And in the directory venv\scripts run these commands
> 
> .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cu130
> 
> .\python.exe -s -m pip install --pre --upgrade --no-cache-dir torchvision --extra-index-url https://download.pytorch.org/whl/cu130
> 
> If first comes with an error just run the second And rerun the first just to be sure that no errors have occurred And you should good to go

 i have this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
blendmodes 2022 requires numpy<2,>=1.22.1, but you have numpy 2.2.6 which is incompatible.
blendmodes 2022 requires Pillow<10,>=9.0.0, but you have pillow 12.1.0 which is incompatible.
gradio 3.41.2 requires markupsafe~=2.0, but you have markupsafe 3.0.2 which is incompatible.
gradio 3.41.2 requires numpy~=1.0, but you have numpy 2.2.6 which is incompatible.
gradio 3.41.2 requires pillow<11.0,>=8.0, but you have pillow 12.1.0 which is incompatible.
numba 0.61.0 requires numpy<2.2,>=1.24, but you have numpy 2.2.6 which is incompatible.
onnx 1.20.1 requires protobuf>=4.25.1, but you have protobuf 3.20.3 which is incompatible.
Successfully installed MarkupSafe-3.0.2 filelock-3.20.3 fsspec-2026.1.0 jinja2-3.1.6 mpmath-1.3.0 networkx-3.4.2 numpy-2.2.6 pillow-12.1.0 sympy-1.14.0 torch-2.11.0.dev20260131+cu130 torchaudio-2.11.0.dev20260131+cu130 torchvision-0.25.0.dev20260131+cu130 typing-extensions-4.15.0

**Comment by PsicomonTamer** [comment]
go to your webui directory example desktop/torch/webui
 in this directory open a cmd window and and run this command Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process
then run the command venv\Scripts\activate
then you should see the venv in green leters in the beginning of the path 
then run the command pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
this should fix the incompatible libraries 
and if needed run the previus commands for torch and torchvision again

**Comment by kirarock** [comment]
> Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau

<img width="703" height="308" alt="Image" src="https://github.com/user-attachments/assets/7b06ea21-c4a8-43cc-8535-804cdf5dd692" />It doesn't work for me

**Comment by PsicomonTamer** [comment]
> > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> 
> <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me

I recommend to reinstall a clean version first backup all your models  and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git
Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py
And Change line 5 to 

target_bitsandbytes_version = '0.49.1'  this is to avoid bitsandbytes downgrade

If you have any other errors you must install the correct library
pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
Etc

**Comment by kirarock** [comment]
> > > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> > 
> > 
> > <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me
> 
> I recommend to reinstall a clean version first backup all your models and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py And Change line 5 to
> 
> target_bitsandbytes_version = '0.49.1' this is to avoid bitsandbytes downgrade
> 
> If you have any other errors you must install the correct library pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Etc

So if I understand correctly, I start from scratch and do this:

Download https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z

Run update.bat and then run.bat.
Go to the command prompt: PS I:\webui_forge_cu121_torch231>
Run: git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git
Then: --index-url https://download.pytorch.org/whl/nightly/cu130

Then, in Notepad++, in the file: modules_forge/bnb_installer.py
Replace line 5 with: target_bitsandbytes_version = '0.49.1'

And if it still doesn't work, run the following command in the command prompt: pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1

Is this correct, or have I completely misunderstood?

**Comment by PsicomonTamer** [comment]
> > > > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> > > 
> > > 
> > > <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me
> > 
> > 
> > I recommend to reinstall a clean version first backup all your models and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py And Change line 5 to
> > target_bitsandbytes_version = '0.49.1' this is to avoid bitsandbytes downgrade
> > If you have any other errors you must install the correct library pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Etc
> 
> So if I understand correctly, I start from scratch and do this:
> 
> Download https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z
> 
> Run update.bat and then run.bat. Go to the command prompt: PS I:\webui_forge_cu121_torch231> Run: git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then: --index-url https://download.pytorch.org/whl/nightly/cu130
> 
> Then, in Notepad++, in the file: modules_forge/bnb_installer.py Replace line 5 with: target_bitsandbytes_version = '0.49.1'
> 
> And if it still doesn't work, run the following command in the command prompt: pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
> 
> Is this correct, or have I completely misunderstood?

No, you have to start from scratch but don't download any zip, you do the command git clone in your desktop and in the root folder of stable-diffusion-webui-forge you must do --index-url https://download.pytorch.org/whl/nightly/cu130 and the next steps,  the git clone command works as if you were downloading the zip

**Comment by kirarock** [comment]
> > > > > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> > > > 
> > > > 
> > > > <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me
> > > 
> > > 
> > > I recommend to reinstall a clean version first backup all your models and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py And Change line 5 to
> > > target_bitsandbytes_version = '0.49.1' this is to avoid bitsandbytes downgrade
> > > If you have any other errors you must install the correct library pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Etc
> > 
> > 
> > So if I understand correctly, I start from scratch and do this:
> > Download https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z
> > Run update.bat and then run.bat. Go to the command prompt: PS I:\webui_forge_cu121_torch231> Run: git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then: --index-url https://download.pytorch.org/whl/nightly/cu130
> > Then, in Notepad++, in the file: modules_forge/bnb_installer.py Replace line 5 with: target_bitsandbytes_version = '0.49.1'
> > And if it still doesn't work, run the following command in the command prompt: pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
> > Is this correct, or have I completely misunderstood?
> 
> No, you have to start from scratch but don't download any zip, you do the command git clone in your desktop and in the root folder of stable-diffusion-webui-forge you must do --index-url https://download.pytorch.org/whl/nightly/cu130 and the next steps, the git clone command works as if you were downloading the zip

<img width="1121" height="1253" alt="Image" src="https://github.com/user-attachments/assets/488b23de-247f-44fd-b4ac-87a08b3659db" />It's progressing, but I'm completely lost.

**Comment by PsicomonTamer** [comment]
> > > > > > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> > > > > 
> > > > > 
> > > > > <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me
> > > > 
> > > > 
> > > > I recommend to reinstall a clean version first backup all your models and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py And Change line 5 to
> > > > target_bitsandbytes_version = '0.49.1' this is to avoid bitsandbytes downgrade
> > > > If you have any other errors you must install the correct library pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Etc
> > > 
> > > 
> > > So if I understand correctly, I start from scratch and do this:
> > > Download https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z
> > > Run update.bat and then run.bat. Go to the command prompt: PS I:\webui_forge_cu121_torch231> Run: git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then: --index-url https://download.pytorch.org/whl/nightly/cu130
> > > Then, in Notepad++, in the file: modules_forge/bnb_installer.py Replace line 5 with: target_bitsandbytes_version = '0.49.1'
> > > And if it still doesn't work, run the following command in the command prompt: pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
> > > Is this correct, or have I completely misunderstood?
> > 
> > 
> > No, you have to start from scratch but don't download any zip, you do the command git clone in your desktop and in the root folder of stable-diffusion-webui-forge you must do --index-url https://download.pytorch.org/whl/nightly/cu130 and the next steps, the git clone command works as if you were downloading the zip
> 
> <img alt="Image" width="1121" height="1253" src="https://private-user-images.githubusercontent.com/45740786/550198910-488b23de-247f-44fd-b4ac-87a08b3659db.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExODQyNzYsIm5iZiI6MTc3MTE4Mzk3NiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxOTg5MTAtNDg4YjIzZGUtMjQ3Zi00NGZkLWI0YWMtODdhMDhiMzY1OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE5MzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjA4NWE1YWZjMjUwYjU4MzkxMjEyODYwNzM1ZmE4MjM5ZWNlZTdiNGU4MGZhYTFmOTRjNmU3MzhmOWZkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KzaTwODuij1FTv3qHyN9Mo5yc9vsOTuV9twDJgdzDLs">It's progressing, but I'm completely lost.

First delete the venv folder, It looks like python is not properly added to the path try reinstalling python and check the box add to path during instalation and If Tha doesn't work, in cmd do where python
And copy that path example C:\Program Files\Python310\python.exe
And in the forge folder do & "C:\Program Files\Python310\python.exe" -m venv venv
That should reconstruct the venv properly then do the commands for  torch cu130  and don't forget to change the bitsandbytes to 49.1 to use in the 5070ti

**Comment by kirarock** [comment]
> > > > > > > Allez dans votre répertoire webui exemple desktop/torch/webui dans ce répertoire ouvrez une fenêtre cmd et exécutez cette commande Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process puis exécutez la commande venv\Scripts\activate alors vous devriez voir le venv en lettres vertes au début du chemin puis exécutez la commande pip install numpy==1.25.0 oreiller==10.0.0" MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Cela devrait corriger les bibliothèques incompatibles et si nécessaire exécuter les commandes précédentes pour la torche et la flambeau à nouveau
> > > > > > 
> > > > > > 
> > > > > > <img alt="Image" width="703" height="308" src="https://private-user-images.githubusercontent.com/45740786/550174864-7b06ea21-c4a8-43cc-8535-804cdf5dd692.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExNzYzNDIsIm5iZiI6MTc3MTE3NjA0MiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxNzQ4NjQtN2IwNmVhMjEtYzRhOC00M2NjLTg1MzUtODA0Y2RmNWRkNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE3MjA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyZGY0NTc4ZTIzMjFmOGQ2NmY5ZTZkY2JjZjQyMzMyZjUyYTg1ZjljYWRkZGZkZGU5NTI5ZDhlZjFhMWM1MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QXFUnlvggJ4FL6MSva-t1gFF37iMdM20OcTMW_-ga_4">It doesn't work for me
> > > > > 
> > > > > 
> > > > > I recommend to reinstall a clean version first backup all your models and checkpoints and delete the forge folder then use this command-> git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then install the desired torch cu -> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130 , now go to modules_forge/bnb_installer.py And Change line 5 to
> > > > > target_bitsandbytes_version = '0.49.1' this is to avoid bitsandbytes downgrade
> > > > > If you have any other errors you must install the correct library pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1 Etc
> > > > 
> > > > 
> > > > So if I understand correctly, I start from scratch and do this:
> > > > Download https://github.com/lllyasviel/stable-diffusion-webui-forge/releases/download/latest/webui_forge_cu121_torch231.7z
> > > > Run update.bat and then run.bat. Go to the command prompt: PS I:\webui_forge_cu121_torch231> Run: git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git Then: --index-url https://download.pytorch.org/whl/nightly/cu130
> > > > Then, in Notepad++, in the file: modules_forge/bnb_installer.py Replace line 5 with: target_bitsandbytes_version = '0.49.1'
> > > > And if it still doesn't work, run the following command in the command prompt: pip install numpy==1.25.0 pillow==10.0.0 "MarkupSafe<3.0,>=2.0" protobuf==4.25.1
> > > > Is this correct, or have I completely misunderstood?
> > > 
> > > 
> > > No, you have to start from scratch but don't download any zip, you do the command git clone in your desktop and in the root folder of stable-diffusion-webui-forge you must do --index-url https://download.pytorch.org/whl/nightly/cu130 and the next steps, the git clone command works as if you were downloading the zip
> > 
> > 
> > <img alt="Image" width="1121" height="1253" src="https://private-user-images.githubusercontent.com/45740786/550198910-488b23de-247f-44fd-b4ac-87a08b3659db.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzExODQyNzYsIm5iZiI6MTc3MTE4Mzk3NiwicGF0aCI6Ii80NTc0MDc4Ni81NTAxOTg5MTAtNDg4YjIzZGUtMjQ3Zi00NGZkLWI0YWMtODdhMDhiMzY1OWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMjE1VDE5MzI1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNjA4NWE1YWZjMjUwYjU4MzkxMjEyODYwNzM1ZmE4MjM5ZWNlZTdiNGU4MGZhYTFmOTRjNmU3MzhmOWZkODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KzaTwODuij1FTv3qHyN9Mo5yc9vsOTuV9twDJgdzDLs">It's progressing, but I'm completely lost.
> 
> First delete the venv folder, It looks like python is not properly added to the path try reinstalling python and check the box add to path during instalation and If Tha doesn't work, in cmd do where python And copy that path example C:\Program Files\Python310\python.exe And in the forge folder do & "C:\Program Files\Python310\python.exe" -m venv venv That should reconstruct the venv properly then do the commands for torch cu130 and don't forget to change the bitsandbytes to 49.1 to use in the 5070ti

I tried to get Gemini to translate everything you told me, and here's what she came up with: Phase 1: Prerequisites (Mandatory)

Before typing any commands, ensure you have these two tools installed:

    Git: [Download here](https://git-scm.com/download/win) (Select "64-bit Git for Windows Setup").

    Python 3.10.6: [Download here](https://www.python.org/downloads/release/python-3106/) (Scroll to the bottom and select "Windows installer (64-bit)").

        IMPORTANT: Check the box "Add Python 3.10 to PATH" during installation.

Phase 2: Installing Forge

Open your terminal (CMD or PowerShell) on your desktop and follow this exact order:

    Clone the files:
    git clone https://github.com/lllyasviel/stable-diffusion-webui-forge.git

    Enter the folder:
    cd stable-diffusion-webui-forge

    Create the virtual environment (venv):
    python -m venv venv

    Activate the environment:

        In PowerShell: .\venv\Scripts\activate

        (If you get a script error: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process then try again)

    Install Torch (specific command):
    pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu130

Phase 3: Modify the file (Anti-downgrade)

    Go to the modules_forge folder using your file explorer.

    Right-click on bnb_installer.py > Edit (with Notepad or Notepad++).

    On line 5 (or where requested), replace the version with:
    target_bitsandbytes_version = '0.49.1'
    (Make sure to include the single quotes ' ' to avoid a SyntaxError).

    Save and close.

Phase 4: First Launch

In your main stable-diffusion-webui-forge folder, double-click on:
webui-user.bat

    Note: The first launch will take some time as it automatically downloads all missing libraries.

**Comment by kirarock** [comment]
I tried to follow along and it didn't change anything:

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by zeydsama** [comment]
just move to this https://github.com/Haoming02/sd-webui-forge-classic

**Comment by Tony3rd** [comment]
BTW, between my post and the first reply, i simply moved to Forge Neo, which is why i didn't reply. If Kirarock still want to use this topic, its okay. (and i didn't need to uninstall anything).

**Comment by kirarock** [comment]
That's what I did, but it doesn't respond as well to my model as this one.

(I find NEO less stable in terms of graphic style.)

**Comment by kirarock** [comment]
It's all good, I fixed it. Starting with the version 'Forge with CUDA 12.1 + Pytorch 2.3.1 <- Recommended', you just had to:

    Go to: \webui_forge_cu121_torch231

    Open a CMD (Command Prompt)

    Run the following command:
    ..\system\python\python.exe -m pip install --upgrade torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128
