### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by gamakila** [lllyasviel/stable-diffusion-webui-forge#3095]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by LMilazzo** [comment]
I was able to fix this issue pretty easy:

The issue is most likely that your installed version came with a pytorch / torchvision version that is not compatible with your gpu/cuda version. In my case I was running a 5080 which is sm_120.

Open terminal and cd into this subdirectory wherever it is on your device:
`cd webui_forge_cu121_torch231\system\`

Next uninstall the packaged torch
`.\python\python.exe -m pip uninstall torch torchvision torchaudio -y`

You should see a message saying torch and torch vision were uninstalled.

Finally install a compatible torch and torchvision version:
`.\python\python.exe -m pip install torch==2.9.1+cu128 torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128`

^ That is the version that I use on my 5080  Driver Version: 577.05 CUDA Version: 12.9. If this version doesnt work either do some research into what version will work with your device you can see your cuda version by running 'nvidia-smi' in a terminal. This is also a useful link: https://pytorch.org/get-started/locally/.

This is just works for me as I encountered a similar issue. However the fix or reason behind why you are seeing the issue may be different so sorry if this doesn't work.

**Comment by zeydsama** [comment]
just move to this https://github.com/Haoming02/sd-webui-forge-classic
